[general]
import = [
    "~/.config/alacritty/font-os.toml"
]

[window]
decorations = "None"
opacity = 1.0

[window.padding]
x = 8
y = 8

[font]
size = 14

[font.normal]
family = "UbuntuSansMonoNerdFont"
style = "Regular"

[font.bold]
family = "UbuntuSansMonoNerdFont"
style = "Bold"

[font.italic]
family = "UbuntuSansMonoNerdFont"
style = "Italic"

[font.bold_italic]
family = "UbuntuSansMonoNerdFont"
style = "Bold Italic"

[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.cursor]
text = "#1d2021"
cursor = "#ebdbb2"

[colors.selection]
text = "#1d2021"
background = "#ebdbb2"

[colors.normal]
black   = '#1d2021'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#d5c4a1'

[colors.bright]
black   = '#665c54'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#fbf1c7'

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Off" }
