#!/usr/bin/env bash

# This script assumes you are using Arch Linux, installed GNU stow and have already done "git clone https://github.com/singhc7/dotfiles ~/dotfiles/"
PACKAGESTOINSTALL=('aria2' 'bat' 'borg' 'btop' 'eza' 'fd' 'firefox' 'fzf' 'jdk-openjdk' 'keepassxc' 'kitty' 'mpv' 'neovim' 'ripgrep' 'rustup' 'syncthing' 'tealdeer' 'thunderbird' 'yt-dlp' 'zoxide' 'zsh')
PACKAGESTOSTOW=('aria2' 'btop' 'eza' 'fzf' 'kitty' 'mpv' 'nnn' 'neovim' 'tealdeer' 'yt-dlp' 'zsh')

# Starts a system upgrade and then install all the non-existing packages using pacman.
if command -V pacman &>/dev/null; then
	echo "Starting system upgrade and package install..."
	if ! sudo pacman -Syu --needed "${PACKAGESTOINSTALL[@]}"; then
		echo "Error: pacman transaction failed. Exiting..."
		exit 1
	fi
	echo "All packages installed successfully."
else
	echo "Warning: pacman not found. Aborting installation."
	exit 1
fi

# Setup symlinks to dotfiles using GNU stow.
echo "Setting up dotfiles..."
cd ~/dotfiles/ || {
	echo "Directory ~/dotfiles/ not found! Exiting."
	exit 1
}
stow -R "${PACKAGESTOSTOW[@]}"

# Install Antidote (zsh plugin manager) into ~/.antidote if missing.
if [[ ! -d ~/.antidote ]]; then
	echo "Installing Antidote..."
	git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
fi

echo "Setup complete!"
